/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppManualRouteImport } from './routes/_app/manual'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStudioRouteImport } from './routes/_app/studio'
import { Route as AppVideoRouteImport } from './routes/_app/video'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppOrdersIdRouteImport } from './routes/_app/orders/$id'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PrintQuoteIdRouteImport } from './routes/print/quote.$id'
import { Route as PrintRequestIdRouteImport } from './routes/print/request.$id'
import { Route as PrintStatementIdRouteImport } from './routes/print/statement.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppManualRoute = AppManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppVideoRoute = AppVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintQuoteIdRoute = PrintQuoteIdRouteImport.update({
  id: '/print/quote/$id',
  path: '/print/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRequestIdRoute = PrintRequestIdRouteImport.update({
  id: '/print/request/$id',
  path: '/print/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintStatementIdRoute = PrintStatementIdRouteImport.update({
  id: '/print/statement/$id',
  path: '/print/statement/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/clients': typeof AppClientsRoute
  '/manual': typeof AppManualRoute
  '/settings': typeof AppSettingsRoute
  '/studio': typeof AppStudioRoute
  '/video': typeof AppVideoRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/print/quote/$id': typeof PrintQuoteIdRoute
  '/print/request/$id': typeof PrintRequestIdRoute
  '/print/statement/$id': typeof PrintStatementIdRoute
  '/orders/': typeof AppOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clients': typeof AppClientsRoute
  '/manual': typeof AppManualRoute
  '/settings': typeof AppSettingsRoute
  '/studio': typeof AppStudioRoute
  '/video': typeof AppVideoRoute
  '/': typeof AppIndexRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/print/quote/$id': typeof PrintQuoteIdRoute
  '/print/request/$id': typeof PrintRequestIdRoute
  '/print/statement/$id': typeof PrintStatementIdRoute
  '/orders': typeof AppOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/manual': typeof AppManualRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/studio': typeof AppStudioRoute
  '/_app/video': typeof AppVideoRoute
  '/_app/': typeof AppIndexRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/print/quote/$id': typeof PrintQuoteIdRoute
  '/print/request/$id': typeof PrintRequestIdRoute
  '/print/statement/$id': typeof PrintStatementIdRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clients'
    | '/manual'
    | '/settings'
    | '/studio'
    | '/video'
    | '/orders/$id'
    | '/orders/new'
    | '/api/auth/$'
    | '/print/quote/$id'
    | '/print/request/$id'
    | '/print/statement/$id'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/clients'
    | '/manual'
    | '/settings'
    | '/studio'
    | '/video'
    | '/'
    | '/orders/$id'
    | '/orders/new'
    | '/api/auth/$'
    | '/print/quote/$id'
    | '/print/request/$id'
    | '/print/statement/$id'
    | '/orders'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/clients'
    | '/_app/manual'
    | '/_app/settings'
    | '/_app/studio'
    | '/_app/video'
    | '/_app/'
    | '/_app/orders/$id'
    | '/_app/orders/new'
    | '/api/auth/$'
    | '/print/quote/$id'
    | '/print/request/$id'
    | '/print/statement/$id'
    | '/_app/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PrintQuoteIdRoute: typeof PrintQuoteIdRoute
  PrintRequestIdRoute: typeof PrintRequestIdRoute
  PrintStatementIdRoute: typeof PrintStatementIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manual': {
      id: '/_app/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof AppManualRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/video': {
      id: '/_app/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof AppVideoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/quote/$id': {
      id: '/print/quote/$id'
      path: '/print/quote/$id'
      fullPath: '/print/quote/$id'
      preLoaderRoute: typeof PrintQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/request/$id': {
      id: '/print/request/$id'
      path: '/print/request/$id'
      fullPath: '/print/request/$id'
      preLoaderRoute: typeof PrintRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/statement/$id': {
      id: '/print/statement/$id'
      path: '/print/statement/$id'
      fullPath: '/print/statement/$id'
      preLoaderRoute: typeof PrintStatementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppManualRoute: typeof AppManualRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudioRoute: typeof AppStudioRoute
  AppVideoRoute: typeof AppVideoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppManualRoute: AppManualRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudioRoute: AppStudioRoute,
  AppVideoRoute: AppVideoRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PrintQuoteIdRoute: PrintQuoteIdRoute,
  PrintRequestIdRoute: PrintRequestIdRoute,
  PrintStatementIdRoute: PrintStatementIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
